site_name: discord-features-handler
site_author: Brandon Ng
site_description: >-
  discord-features-handler npm package official documentation website
copyright: Copyright &copy; 2022 - 2025 discord-features-handler
nav:
  - Discord-Features-Handler: index.md
  - Getting started:
      - Installation: getting-started/installation.md
      - Environment Variables: getting-started/environment-variables.md
      - Folder Structure: getting-started/folder-structure.md
      - Bot Script File: getting-started/Bot Script file.md
      - TypeScript Support: getting-started/TypeScript Support.md
  - Setup:
      - DiscordFeaturesHandlerOptions: setup/DiscordFeaturesHandlerOptions.md
      - Config file: setup/config-file.md
      - Slash command files: setup/slash-commands-file.md
      - Prefix command files: setup/commands-file.md
      - Other interactions: setup/other-interaction.md
      - Event files: setup/events-file.md
      - Modules file: setup/modules-files.md
  - Built-in Features:
      - MessageCreate event: builtIn/messageCreate-event.md
      - InteractionCreate event: builtIn/interactionCreate-event.md
      - Help command: builtIn/help-command.md
      - Reload command: builtIn/reload-command.md
      - Functions: builtIn/functions.md
      - Disabling built in: builtIn/disabling-built-in-features.md
  - Demo: demo.md
  - About: about.md
  - Release Notes: release-notes.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.footnote.tooltips
    - navigation.indexes
    - navigation.sections
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/moon-waning-crescent
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - social
  - search
  - tags

extra:
  analytics:
    provider: google
    property: ${{secrets.GOOGLE_ANAYLTICS}}
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/bng94/discord-features-handler
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/package/discord-features-handler

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
